server:
  # Auth Service 실행 포트
  port: 19092

spring:
  application:
    # Eureka에 등록되는 서비스 이름
    # Gateway의 lb://auth-service와 반드시 일치해야 합니다.
    name: auth-service

  config:
    # auth-service 디렉터리를 실행 경로로 사용할 경우
    # 프로젝트 루트의 .env 파일을 불러옵니다.
    import: "optional:file:../.env[.properties]"

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    # Auth Service를 Eureka Server에 등록
    register-with-eureka: true
    # Eureka Registry에서 다른 서비스 목록 조회
    fetch-registry: true

    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:19090/eureka}

jwt:
  issuer: auth-service
  private-key-path: ${JWT_PRIVATE_KEY_PATH}
  public-key-path: ${JWT_PUBLIC_KEY_PATH}
  access-token-expiration: 30m
  refresh-token-expiration: 8h

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

    zipkin:
      tracing:
        endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.boot.context.config: DEBUG

  pattern:
    console: '%clr(%-5level){green} [traceId=%X{traceId:-}, spanId=%X{spanId:-}] %clr(%logger{36}.%M()){cyan}: %msg%n'