server:
  port: 19099

gemini:
  api-key: ${GEMINI_API_KEY}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent

spring:
  application:
    name: notification-service

  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    discovery:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:19090/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.boot.context.config: DEBUG
  pattern:
    console: '%clr(%-5level){green} [traceId=%X{traceId:-}, spanId=%X{spanId:-}] %clr(%logger{36}){cyan}: %msg%n'

outbox:
  publisher:
    fixed-delay: 1000

slack:
  bot-token: ${SLACK_BOT_TOKEN}