spring:
  application:
    name: inventory-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port:
    19100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info