spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${INVENTORY_SERVICE_PORT:19100}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true

  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

logging:
  level:
    com.sixro.logistics.inventory: INFO