spring:
  application:
    name: inventory-service

  datasource:
    url: ${INVENTORY_DB_URL}
    username: ${INVENTORY_DB_USERNAME}
    password: ${INVENTORY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER_URL}
      group-id: inventory-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      bootstrap-servers: ${KAFKA_SERVER_URL}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 19100

eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:19090/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info