spring.application.name=delivery-service
server.port=19097

eureka.client.service-url.defaultZone= http://localhost:19090/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/delivery
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.tracing.export.zipkin.enabled=false