name: CI Pipeline

on:
  pull_request:
    branches: [ "develop", "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

# CI 진행 중에 새로운 push가 올라오는 경우, 이전 CI 워크플로우를 취소하여 리소스 절약
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# GitHub repo 읽기 권한만 부여
permissions:
  contents: read

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    # 타임 아웃 15분 설정
    timeout-minutes: 15

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 어떤 파일이 변경되었는지 비교하기 위해 전체 커밋 히스토리를 가져오기

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # Gradle 캐싱 및 빌드 최적화

      # PR이 올라오면 변경된 파일을 확인해서 해당 서비스만 build
      - name: Get changed files
        if: github.event_name == 'pull_request'
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Determine affected modules
        id: analyze
        env:
          EVENT_NAME: ${{ github.event_name }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        shell: bash
        run: |

          # main에 push되면 전체 build
          if [[ "$EVENT_NAME" == "push" ]]; then
            echo "TASKS=build" >> $GITHUB_OUTPUT
            exit 0
          fi

          RUN_ALL=false
          MODULES=()

          for file in $CHANGED_FILES; do

            # common-module, root 의 gradle 설정, workflows 변경시, 전체 build
            case "$file" in
              common-module/*|settings.gradle|build.gradle|gradle/*|.github/workflows/*)
                RUN_ALL=true
                break
                ;;
            esac

            # 서비스 모듈명 추출 후 build.gradle 존재하면 추가
            module=$(echo "$file" | cut -d/ -f1)

            if [[ -f "$module/build.gradle" ]]; then
              MODULES+=("$module")
            fi

          done

          if [[ "$RUN_ALL" == true ]]; then
            echo "TASKS=build" >> $GITHUB_OUTPUT
            exit 0
          fi

          # 모듈 목록에서 중복 제거
          UNIQUE=$(printf "%s\n" "${MODULES[@]}" | sort -u)

          # 변경된 백엔드 모듈이 없다면 CI 종료
          if [[ -z "$UNIQUE" ]]; then
            echo "TASKS=none" >> $GITHUB_OUTPUT
            exit 0
          fi

          TASKS=""

          # 변경된 특정 서비스만 build
          while IFS= read -r module
          do
            [[ -z "$module" ]] && continue
            TASKS="$TASKS :$module:build"
          done <<< "$UNIQUE"

          echo "TASKS=$TASKS" >> $GITHUB_OUTPUT

      - name: Grant execute permission
        if: steps.analyze.outputs.TASKS != 'none'
        run: chmod +x gradlew

      - name: Run Build
        if: steps.analyze.outputs.TASKS != 'none'
        run: ./gradlew ${{ steps.analyze.outputs.TASKS }} --parallel --build-cache

      # 만약 빌드/테스트가 실패시, 에러 리포트 파일 GitHub Actions에 업로드
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            **/build/reports/tests/**
            **/build/test-results/**